### ISSUE TITLE
Script working? 

### ISSUE THREAD

**Issue by uros76** [Boondoggler3210/OBS-Zwift-Ride-Ons#1]
Hi. I added the script to OBS and edited settings but nothing happens. The script log looks empty too. 
Am I doing something wrong or this stopped working with the latest Zwift updates?

**Comment by Boondoggler3210** [comment]
Hi, 

Have you had the script working OK previously? Which settings have you edited and what version of OBS are you using? 

I' haven't had chance to test using the latest version of Zwift yet, so it's possible there is an issue there.

**Comment by uros76** [comment]
This is the first time I use it. I just added the path to the zwift log and some output files. Nothing else. 
I am using the latest OBS v26. 
Ok, can you pls check so I don't spend hours trying :D

**Comment by Boondoggler3210** [comment]
Just gave it a quick test in OBS 26 with an old Zwift log and that works fine, so it's not an OBS update issue.  I'll try with latest Zwift when i get a minute later.

**Comment by Boondoggler3210** [comment]
Quick test after updating Zwift looks like it works fine.

![image](https://user-images.githubusercontent.com/65829427/95087054-1e5e3780-0719-11eb-9326-be8f13389504.png)

Maybe paste up a copy of your OBS layout and script settings in case I can see a problem?

**Comment by uros76** [comment]
Here is a simple new profile with one scene and just text files linked to the script. Somehow I am not getting anything through :( 

![image](https://user-images.githubusercontent.com/25409772/95129285-1b843680-075b-11eb-827f-371d2f0028b3.png)

**Comment by Boondoggler3210** [comment]
Thing that stands out with the fields you have selected is that they will only populate if there are entries in the log file, if not you won't see anything. 

It's probably worth clarifying that the sources won't populate with 'Ride Ons Received:' or anything like that, just the number, in my example i added those labels in separate text sources.

Zwift creates a new log file every time you load it up, so if you loaded it and didn't ride (maybe when testing the script), the last log won't have data for any of those entries potentially.  Easiest test is to add a source for Total Ride Ons or Total Ride Ons given.  That way you should get a zero even if there is nothing in the file. If those work, the others should as well as soon as there is data in the log file.

Another easy way to test it is to use the Current route source - map this to a text source and load up Zwift, select a route - that will populate as soon as one is selected in the route selector.  If that works the others should too.

Hope that helps, thanks

**Comment by uros76** [comment]
Thanks for all the help. I tried everything possible but still doesn't work. Don't know what's wrong but probably something on my end. I might try on different pc and see if I manage to get it working there.

**Comment by uros76** [comment]
I just tested on another pc and no luck either. I believe I am doing all settings right, just no success. 

Here is my current test just focusing on the route name to get through... 
![image](https://user-images.githubusercontent.com/25409772/95173036-7304bf80-07b8-11eb-9417-25365af74da8.png)

**Comment by Boondoggler3210** [comment]
HI, I've tried mirroring your settings and can't get it to break:

![image](https://user-images.githubusercontent.com/65829427/95215871-63519f00-07e9-11eb-8150-2a2659c0f223.png)

Can you attach a copy of your log file? I'll can try loading you log and see what i get incase for some reason there's a difference in the files

Cheers,

**Comment by uros76** [comment]
That's really strange. Almost like something is preventing the script to run. 

Sure, here is one of the logs, from yesterday group workout ride: 
[Log.txt](https://github.com/Boondoggler3210/OBS-Zwift-Ride-Ons/files/5338669/Log.txt)

**Comment by Boondoggler3210** [comment]
Very odd, works fine here:
![image](https://user-images.githubusercontent.com/65829427/95307436-8aa77b00-0880-11eb-8198-f7c7a32f884a.png)

The screenshot above is from a  different PC than the screenshots from the other posts, this log works ok no both machines.  It's the first time I've seen it behave like this, not sure what else to suggest you try.

**Comment by uros76** [comment]
Oh wow. That is so weird. I did try it on two computers and couldn't get it to work. The second PC even has a fresh OBS installed. 
Is there some dependency I might be missing? .NET, python...? 

I will try it on third pc later today. Maybe third's a charm :D 
Update: third also failed to work. 

Thanks for all the quick help.

**Comment by Boondoggler3210** [comment]
No dependencies that I'm aware of.  Lua's built into OBS and the script only uses native Lua and the OBS API functions, so doesn't need anything external.

**Comment by uros76** [comment]
Ok, thanks a lot for debugging and trying to find a solution. I have no clue what's up with my computers not working. 
Anyway, let's close this as I know it works for others. Just must be something on my side...
